config/routes.rb
Rails.application.routes.draw do

  root "chats#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :chats

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat

  validates :field, presence: true, length: {minimum: 2, maximum: 500}

  after_create_commit { MessageBroadcastJob.perform_later(self) }

  def create_date
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :vkontakte]
  has_and_belongs_to_many :chats
  has_many :messages, dependent: :destroy

  def name
    email.split('@')[0]
  end

  def online?
    updated_at > 5.minutes.ago
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  after_filter :user_activity

  private

  def user_activity
    current_user.try :touch
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :users_all, only: [:index, :new]

  def index
    @chats = current_user.chats.all.reverse
  end

  def show
    @chat = Chat.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end
  
  def new
    @chat = Chat.new
  end

  def create
    @chat = Chat.new
    if @chat.save
      second_user_id = params[:chat][:users].select {|key,value| key == 'check'}.values
      add_user = User.find(second_user_id)
      @chat.users << current_user << add_user
      flash[:notice] = "Chat created successful"
      redirect_to chat_path(@chat.id)
    else
      flash[:error] = "Something wrong"
      render 'new'
    end
  end

  private

  def users_all
    @users = User.all.reverse
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def all
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Soc Network") if is_navigational_format?
    else
      session["devise.all_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  alias_method :vkontakte, :all
  alias_method :facebook, :all

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/_chat.html.haml
%li= link_to "Enter chat № #{chat.id}", chat_path(chat)

app/views/chats/_form.html.haml
= simple_form_for @chat do |f|
  - @users.each do |user|
    %p
      - if user != current_user
        = f.fields_for :users do |ff|
          = ff.radio_button :check, user.id 
        = user.email
  = f.button :submit, class: 'btn btn-primary'

app/views/chats/index.html.haml
.row
  .col-md-5.column
    %h2 Available Users
    - @users.each do |user|
      %p
        = user.email
        - if user_signed_in? && user.online?
          %span#online_status Online
        - else
          %span#offline_status Offline
  .col-md-6.column
    %h2 Your Chats
    %p= link_to 'Create new chat', new_chat_path, class: 'btn btn-primary'
    %ul
      = render @chats

app/views/chats/new.html.haml
%h2 Add new chat
= render 'form'

app/views/chats/show.html.haml
#messages{"data-chat-id" => "#{@chat.id}"}
  = render @chat.messages
= render 'messages/form'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateChats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<div id="notices">
      <%= render "shared/notices" %>
    </div>

    <div class="container">
      <%= render "shared/header" %>
    
    <div class="buttons">
      <p><a href="http://localhost:3000/races/4/export_results.xml">XML</a></p>
      <p><a href="http://localhost:3000/races/4/export_results.pdf">PDF</a></p>
      <p><a href="http://localhost:3000/races/4/export_results.csv">CSV</a></p>
      <p><a href="http://localhost:3000/races/4/export_results.json">JSON</a></p>
    </div>
    <div id="container">
    </div>

      <%= yield %>
    
    </div>
  </body>
</html>

app/views/messages/_form.html.haml
= simple_form_for @message, url: '#' do |f|
  = f.input :field, placeholder: 'Write your message', class: 'form-control'
  = f.button :submit, class: 'btn btn-primary'

app/views/messages/_message.html.haml
.card
  .row
    .col-md-11
      %p.card-text
        %span.text-muted
          = message.user.name
          at #{message.create_date} says
        %br/
        = message.field

app/views/shared/_header.html.haml
.navbar
  - if current_user
    %p
      You log in as #{current_user.email}
      \#{link_to "Sign Out", destroy_user_session_path, :method => :delete, :class => "btn btn-danger btn-sm"}
  - else
    %p 
      Log in with you social network
      = link_to "Vk Log In", user_vkontakte_omniauth_authorize_path, :class => "btn btn-primary btn-sm"
      = link_to "Fb Log In", user_facebook_omniauth_authorize_path, :class => "btn btn-primary btn-sm"
      or just use your email to
      = link_to "Sign Up", new_user_registration_path, :class => "btn btn-primary btn-sm"
      or
      = link_to "Log In", new_user_session_path, :class => "btn btn-primary btn-sm"

app/views/shared/_notices.html.haml
- if flash[:notice]
  .alert.alert-success= flash[:notice]
- if flash[:error]
  .alert.alert-danger= flash[:error]